import Container from "@/components/shared/Container";
import qs from "qs";
import { fetchAPI } from "@/lib/fetch-api";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import CardList from "@/components/shared/Catalog/Card-List/CardList";

export const metadata: Metadata = {
  title: "Catalog page",
  description: "Generated by create next app",
};

export const dynamicParams = false;

type Props = {
  params: Promise<{ locale: string }>;
};

const createQueryCatalog = (locale: string) =>
  qs.stringify({
    locale: locale,
    fields: ["name", "description", "slug", "locale"],
    populate: {
      image: {
        fields: ["url", "alternativeText"],
      },
    },
  });

async function getCatalog(locale: string) {
  const query = createQueryCatalog(locale);
  const data = await fetchAPI(`/api/categories?${query}`, {
    method: "GET",
    next: {
      revalidate: 60,
    },
  });

  if (!data) notFound();

  // const blocks = data?.data?.blocks || [];
  // return { blocks };

  return data?.data || null;
}

export default async function CatalogPage({ params }: Props) {
  const { locale } = await params;

  const data = await getCatalog(locale);

  return (
    <section>
      <Container>
        <h1 className="text-4xl font-bold pb-10 text-center">
          <span className="text-yellow-500"> Locale: {locale}</span>
        </h1>
        <CardList data={data} />
      </Container>
    </section>
  );
}
