import type { Metadata } from "next";
import EquipmentList from "@/components/shared/blocks/EquipmentList";
import Container from "@/components/shared/Container";

export const metadata: Metadata = {
  title: "Catalog page",
  description: "Generated by create next app",
};

type Props = {
  params: Promise<{ locale: string }>;
};

export default async function CatalogPage({ params }: Props) {
  const { locale } = await params;

  return (
    <>
      <Container>
        <h1 className="text-6xl font-bold my-8">Equipment catalog</h1>
      </Container>
      <EquipmentList locale={locale} />
    </>
  );
}
