import type { Metadata } from "next";
import Header from "@/components/shared/Header";
import { notFound } from "next/navigation";
import { getLocalsStrapi } from "@/lib/strapi";

export const metadata: Metadata = {
  title: "Main page",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export const revalidate = 60;

export async function generateStaticParams(): Promise<{ locale: string }[]> {
  const locales = await getLocalsStrapi();

  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ params, children }: Props) {
  const { locale } = await params;

  const locales = await getLocalsStrapi();

  // Проверка локали
  if (!locales.includes(locale)) notFound(); // Возвращаем ошибку 404, если локаль не существует

  return (
    <html lang={locale}>
      <body>
        <Header locale={locale} />
        <main>{children}</main>
      </body>
    </html>
  );
}
