import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const {l}
  return (
    <html lang={params.lang}>
      <body>
        {children}
      </body>
    </html>
  );
}
