import type { Metadata } from "next";
import Header from "@/components/shared/Header";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { fetchAPI } from "@/lib/fetch-api";
import type { Locales } from "@/interfaces/locales";

export const metadata: Metadata = {
  title: "Main page",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export const dynamicParams = false;

export async function generateStaticParams(): Promise<{ locale: string }[]> {
  const data: Locales[] = await fetchAPI(`/api/i18n/locales`, {
    method: "GET",
    next: {
      revalidate: 60,
    },
  });

  if (!data) notFound();

  return data.map((locale) => ({
    locale: locale.code,
  }));
}

export default async function MainLayout({ params, children }: Props) {
  const { locale } = await params;

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Header locale={locale} />
          <main>{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
